# Arquivo separado só para manter as equipes
EQUIPES = {
    "LETÍCIA":[
        {"NOME":"Letícia Nascimento Santos de Lima","FUNÇÃO":"ENCARREGADO DE TI"},
        {"NOME":"","FUNÇÃO":""},
    ],
    "LICURI": [  
        {"NOME": "ALAOR DIAS CAMPOS", "FUNÇÃO": "SUPERVISOR DE MONTAGEM"},  
        {"NOME": "RAIMUNDO FELIX DE ALMEIDA", "FUNÇÃO": "ENCARREGADO DE TUBULAÇÃO"},  
        {"NOME": "ANTONIO RAIMUNDO RIBEIRO FILHO", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "VANDERLEY FRANCISCO SANTOS", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "EDMILSON MUNIZ DOS SANTOS JUNIOR", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "EDSON FERREIRA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "JOSE GABRIEL DE ALMEIDA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "CLEBER ALVES", "FUNÇÃO": "SOLDADOR TIG/ER"},  
        {"NOME": "REGINALDO ROCHA DA SILVA", "FUNÇÃO": "SOLDADOR TIG/ER"},  
        {"NOME": "FRANCISCO YURI DE SOUSA OLIVEIRA", "FUNÇÃO": "AJUDANTE"},  
        {"NOME": "GEOVANI CARVALHO", "FUNÇÃO": "AJUDANTE"},  
        {"NOME": "ANTÔNIO CARLOS", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "VALMIR MARCIANO", "FUNÇÃO": "MECÂNICO"},  
        {"NOME": "ROBERT RICARDO", "FUNÇÃO": "SOLDADOR TIG/ER"}  
    ],  

    "IUDE": [  
        {"NOME": "ALAOR DIAS CAMPOS", "FUNÇÃO": "SUPERVISOR DE MONTAGEM"},  
        {"NOME": "IUDE JOSE GILES", "FUNÇÃO": "ENCARREGADO DE TUBULAÇÃO"},  
        {"NOME": "EDI CARLOS ARLINDO FRANCO", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "FRANCISCO DE BRITO PERES", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "JAIRO COLMAN", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "JAILSON", "FUNÇÃO": "SOLDADOR TIG/ER"},  
        {"NOME": "MANUEL MESSIAS NOVAIS", "FUNÇÃO": "SOLDADOR TIG/ER"},  
        {"NOME": "IZAQUIEL LUIS DA SILVA", "FUNÇÃO": "SOLDADOR TIG/ER"},  
        {"NOME": "ALVERTINO MÁXIMO", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "ANTÔNIO LUIS", "FUNÇÃO": "SOLDADOR TIG/ER"},  
        {"NOME": "GENILDO", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "YAGO BORGES", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "DAVI SILVA", "FUNÇÃO": "LIXADOR"},  
        {"NOME": "LUIZ R", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "ADRIANO SOUZA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "RONALDO DOS SANTOS", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "JOSE ROBERTO MACEDO", "FUNÇÃO": "SOLDADOR TIG/ER"}  
    ],  

    "CHIQUINHO": [  
        {"NOME": "ALAOR DIAS CAMPOS", "FUNÇÃO": "SUPERVISOR DE MONTAGEM"},  
        {"NOME": "FRANCISCO DA CHAGAS CARVALHO DE ARAUJO", "FUNÇÃO": "ENCARREGADO DE TUBULAÇÃO"},  
        {"NOME": "JORGE PEREIRA DA SILVA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "ANTONIO BENICIO DA SILVA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "VALDECIR FERREIRA FOSSAT", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "FRANCISCO RODRIGUES REZENDES", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "SANDRO COPETTI AGERTT", "FUNÇÃO": "SOLDADOR TIG/ER"},  
        {"NOME": "ERIVAN CHAGAS MAGALHÃES DA SILVA", "FUNÇÃO": "SOLDADOR TIG/ER"},  
        {"NOME": "JAIR RODRIGUES DE OLIVEIRA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "DAVID APARECIDO", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "SIDNEI ALEX", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "WELLINGTON TEIXEIRA", "FUNÇÃO": "AJUDANTE"},  
        {"NOME": "WEMERSON", "FUNÇÃO": "AJUDANTE"}  
    ],  

    "DEDÉ": [  
        {"NOME": "ALAOR DIAS CAMPOS", "FUNÇÃO": "SUPERVISOR DE MONTAGEM"},  
        {"NOME": "WELLINGHTON MARTINS", "FUNÇÃO": "ENCARREGADO DE TUBULAÇÃO"},  
        {"NOME": "ANTÔNIO DOS SANTOS", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "VICTOR CAVALCANTE", "FUNÇÃO": "AJUDANTE"},  
        {"NOME": "CICERO DE SOUZA", "FUNÇÃO": "AJUDANTE"},  
        {"NOME": "JADAELSON", "FUNÇÃO": "SOLDADOR TIG/ER"},  
        {"NOME": "FRANCISCO DE ASSIS", "FUNÇÃO": "SOLDADOR TIG/ER"},  
        {"NOME": "JOSÉ WILSON", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "HIGOR TAYLAN", "FUNÇÃO": "AJUDANTE"},  
        {"NOME": "PEDRO LIMA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"}  
    ],  
    "MAGALHAES": [  
        {"NOME": "ALAOR DIAS CAMPOS", "FUNÇÃO": "SUPERVISOR DE MONTAGEM"},  
        {"NOME": "JOSÉ DA SILVA MAGALHÃES", "FUNÇÃO": "ENCARREGADO DE TUBULAÇÃO"},  
        {"NOME": "AURÉLIO PEREIRA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "OZIEL DA CRUZ", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "SILVIO", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "DAVID", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "JOAQUIM APARECIDO VAZ PEREIRA", "FUNÇÃO": "SOLDADOR TIG/ER"},  
        {"NOME": "JOAQUIM", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "FRANCISMAR", "FUNÇÃO": "SOLDADOR TIG/ER"},  
        {"NOME": "NATAL", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "ANTÔNIO JOSÉ", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "ANTÔNIO", "FUNÇÃO": "ENCANADOR INDUSTRIAL"}  
    ],  

    "RENILDO": [  
        {"NOME": "SUPERVISOR", "FUNÇÃO": "SUPERVISOR DE MONTAGEM"},  
        {"NOME": "RENILDO DOS SANTOS", "FUNÇÃO": "ENCARREGADO DE TUBULAÇÃO"},  
        {"NOME": "GLAUBERSON", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "WELLINGTON", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "CLEUSON SENA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "VANDERLEI", "FUNÇÃO": "ENCANADOR INDUSTRIAL"}  
    ],  

    "JOSE": [  
        {"NOME": "SUPERVISOR", "FUNÇÃO": "SUPERVISOR DE MONTAGEM"},  
        {"NOME": "JOSE JORGE ROCHA", "FUNÇÃO": "ENCARREGADO DE TUBULAÇÃO"},  
        {"NOME": "ADRIANO DE JESUS", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "ELEMILTON MOREIRA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "JAILSON ADALBERTO", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "JAIME BARBOSA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "JORGE FERNANDES", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "WAGNER MARQUES", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "VALMIR ARAGÃO", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "JOSÉ TIBURCIO", "FUNÇÃO": "ENCANADOR INDUSTRIAL"}  
    ],  

    "ADRIANO": [  
        {"NOME": "SUPERVISOR", "FUNÇÃO": "SUPERVISOR DE MONTAGEM"},  
        {"NOME": "ADRIANO CARVALHO", "FUNÇÃO": "ENCARREGADO DE TUBULAÇÃO"},  
        {"NOME": "FRANCISCO REZENDE", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "ADAILTON NASCIMENTO", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "JOSÉ CARLOS", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "ANTONIO MARCIO", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "ALEXANDRE BARBOSA", "FUNÇÃO": "SOLDADOR TIG/ER"}  
    ],  

    "GEORGE": [  
        {"NOME": "SUPERVISOR", "FUNÇÃO": "SUPERVISOR DE MONTAGEM"},  
        {"NOME": "GEORGE ANUNCIAÇÃO SANTOS", "FUNÇÃO": "ENCARREGADO DE TUBULAÇÃO"},  
        {"NOME": "WALLEX VIANA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "ANDERSON DA PORIFICAÇÃO BANDEIRA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "BENITIZ", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "RAMMON FERREIRA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "DENILSON REIS SOUSA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "JAILTON PEREIRA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "SUENIL DE SOUZA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "JOSENALDO CARVALHO", "FUNÇÃO": "ENCANADOR INDUSTRIAL"}  
    ],  

    "VALMIR": [  
        {"NOME": "SUPERVISOR", "FUNÇÃO": "SUPERVISOR DE MONTAGEM"},  
        {"NOME": "VALMIR DOS SANTOS", "FUNÇÃO": "ENCARREGADO DE TUBULAÇÃO"},  
        {"NOME": "EDISON FERREIRA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "ANTONIO CARLOS DE OLIVEIRA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "ADERALDE ALVES", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},  
        {"NOME": "ANTONIO BEZERRA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"}  
    ],  
    #ANDAIME
    "JOAO": [  
        {"NOME": "RUY CRUZ NUNES", "FUNÇÃO": "SUPERVISOR DE ANDAIME"},  
        {"NOME": "JOAO PAULO NUNES DA SILVA", "FUNÇÃO": "ENCARREGADO DE ANDAIME"},  
        {"NOME": "MARCUS AURELIO SILVA DE OLIVEIRA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "ELIZEU MORENO", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "JOAO BATISTA PLACIDO", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "LUCAS RODOLFO OLIVEIRA MEIRELLE ARNOU", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "ANDRÉ LUIS GONÇALVES", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "RANGEL ALEXANDRO ANJOS DA SILVA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "FRANCISCO JAILSON", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "CESARNILDO", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "MARCELO HUGO", "FUNÇÃO": "MONTADOR DE ANDAIME"}  
    ],  

    "ANTONIO": [  
        {"NOME": "RUY CRUZ NUNES", "FUNÇÃO": "SUPERVISOR DE ANDAIME"},  
        {"NOME": "ANTONIO JOSE PEREIRA BARROS", "FUNÇÃO": "ENCARREGADO DE ANDAIME"},  
        {"NOME": "JOSÉ LUIZ RIBEIRO DA SILVA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "GEREMIAS DE SOUSA COSTA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "KELSON SOUSA SOARES", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "DOMINGOS PEREIRA DA SILVA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "LUAN RODRIGUES DOS SANTOS", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "MARCOS DANIEL", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "CAIQUE MENDONÇA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "RONILSON DE SOUZA BARBOSA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "JOSE LUIS", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "RONILSON DE SOUZA", "FUNÇÃO": "MONTADOR DE ANDAIME"}  
    ],  

    "JOSECI": [  
        {"NOME": "RUY CRUZ NUNES", "FUNÇÃO": "SUPERVISOR DE ANDAIME"},  
        {"NOME": "JOSECI", "FUNÇÃO": "ENCARREGADO DE ANDAIME"},  
        {"NOME": "JURACI SOUZA COSTA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "JOSÉ LUIZ", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "FERNANDO RUFINO", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "LIMARCIO VIEIRA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "DOMIREZ CARMO", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "JOSÉ WILON COSTA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "ATEVALDO ARAUJO SOUSA", "FUNÇÃO": "MONTADOR DE ANDAIME"}  
    ],  

    "CÉLIO": [  
        {"NOME": "RUY CRUZ NUNES", "FUNÇÃO": "SUPERVISOR DE ANDAIME"},  
        {"NOME": "CÉLIO DANTAS DE SOUZA", "FUNÇÃO": "ENCARREGADO DE ANDAIME"},  
        {"NOME": "JOSÉ HILTON DE SOUSA ROCHA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "ANTÔNIO SEBASTIÃO RAMOS DA CUNHA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "WILLIAM LIMA DE SOUSA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "JAIR SANTANA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "ALLAN JORGE DO PRADO", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "ELIVELTON MIRANDA DE OLIVEIRA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "PAULO SÉRGIO", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "ANÉSIO DE PAULA", "FUNÇÃO": "MONTADOR DE ANDAIME"}  
    ],  

    "MARCIEL": [  
        {"NOME": "RUY CRUZ NUNES", "FUNÇÃO": "SUPERVISOR DE ANDAIME"}, 
        {"NOME": "MARCIEL CONCEIÇÃO SANTOS", "FUNÇÃO": "ENCARREGADO DE ANDAIME"}, 
        {"NOME": "ROBERT REINAN", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "WELLINGTON DUTRA", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "DHONHES DIONISIO", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "CLEITON GUIMARÃES", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "JAIR SANTANA DE JESUS", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "LOURIVALDO JESUS ARAUJO", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "JOÃO LUIZ", "FUNÇÃO": "MONTADOR DE ANDAIME"},  
        {"NOME": "JOSÉ JOAQUIM", "FUNÇÃO": "MONTADOR DE ANDAIME"},
        {"NOME": "EDUARDO CAETANO", "FUNÇÃO": "MONTADOR DE ANDAIME"},
        {"NOME": "ERIVALDO DE JESUS", "FUNÇÃO": "MONTADOR DE ANDAIME"},
    ],  
    #ELÉTRICA
    "RAIMUNDO": [  
        {"NOME": "RAFAEL FARIA", "FUNÇÃO": "ENG. ELETRICISTA"},  
        {"NOME": "RÉGIS TRAJANO", "FUNÇÃO": "SUPERVISOR DE ELÉTRICA/INSTRUMENTAÇÃO"},  
        {"NOME": "RAIMUNDO", "FUNÇÃO": "ENCARREGADO ELÉTRICA"},  
        {"NOME": "ALEXANDRE PEREIRA LIMA", "FUNÇÃO": "ELETR. MONTADOR"},  
        {"NOME": "FÁBIO CLAUDINO GONÇALVES", "FUNÇÃO": "AJUDANTE"},  
        {"NOME": "JÚLIO", "FUNÇÃO": "ELETRICISTA F/C"},  
        {"NOME": "WANDERSON ALVES DE OLIVEIRA", "FUNÇÃO": "ELETR.MONTADOR"},  
        {"NOME": "ADAIR", "FUNÇÃO": "ELETRICISTA F/C"},  
        {"NOME": "JONE CASSIO", "FUNÇÃO": "ELETRICISTA F/C"},  
        {"NOME": "FABRICIO CONCEIÇÃO", "FUNÇÃO": "ELETR.MONTADOR"},  
        {"NOME": "MAURO JEAN DE MACEDO", "FUNÇÃO": "ELETR.MONTADOR"},  
        {"NOME": "JOSÉ FRANCISCO DE SOUZA", "FUNÇÃO": "ELETR.MONTADOR"},  
        {"NOME": "WILSON SOUZA DE JESUS", "FUNÇÃO": "ELETR.MONTADOR"},  
        {"NOME": "LUCAS", "FUNÇÃO": "INSTRUMENTISTA"},  
        {"NOME": "EDMAR", "FUNÇÃO": "ELETRICISTA DE MANUTENÇÃO"},  
        {"NOME": "FERNANDO CAMPOS NUNES", "FUNÇÃO": "AJUDANTE"},  
        {"NOME": "SERGIO CARDOSO PEREIRA", "FUNÇÃO": "ELETRICISTA F/C"},  
        {"NOME": "ANTONIO JERONIMO DA SILVA", "FUNÇÃO": "ELETRICISTA DE MANUTENÇÃO"}  
    ],  

    "GILSON": [  
        {"NOME": "RAFAEL FARIA", "FUNÇÃO": "ENG. ELETRICISTA"},  
        {"NOME": "RÉGIS TRAJANO", "FUNÇÃO": "SUPERVISOR DE ELÉTRICA/INSTRUMENTAÇÃO"},  
        {"NOME": "GILSON MONTELO DA SILVA", "FUNÇÃO": "ENCARREGADO INSTRUMENTAÇÃO"},  
        {"NOME": "FELIPE", "FUNÇÃO": "ELETR.MONTADOR"},  
        {"NOME": "ANTÔNIO FRANCISCO R. DA SILVA", "FUNÇÃO": "ELETR. MONTADOR"},  
        {"NOME": "RONIVON DE SOUZA", "FUNÇÃO": "ELETR. MONTADOR"},  
        {"NOME": "PAULO", "FUNÇÃO": "ELETR. MONTADOR"},  
        {"NOME": "ABNOAN DOS SANTOS SILVA", "FUNÇÃO": "ELETR. MONTADOR"},  
        {"NOME": "MANUEL PIMENTEL MIRANDA", "FUNÇÃO": "INSTRUMENTISTA"},  
        {"NOME": "JOÃO MARQUES", "FUNÇÃO": "INSTRUMENTISTA"}  
    ],  

    "REGINALDO": [  
        {"NOME": "RAFAEL FARIA", "FUNÇÃO": "ENG. ELETRICISTA"},  
        {"NOME": "RÉGIS TRAJANO", "FUNÇÃO": "SUPERVISOR DE ELÉTRICA/INSTRUMENTAÇÃO"},  
        {"NOME": "REGINALDO SANTOS DO SACRAMENTO", "FUNÇÃO": "ENCARREGADO DE ELÉTRICA"},  
        {"NOME": "ADEMADIO FERNANDO DOS SANTOS", "FUNÇÃO": "ELETRICISTA F/C"},  
        {"NOME": "CARLOS HENRIQUE S.S. NASCIMENTO", "FUNÇÃO": "ELETRICISTA F/C"},  
        {"NOME": "MAILON SANTOS SOUZA", "FUNÇÃO": "ELETRICISTA F/C"},  
        {"NOME": "ADALBERTO GONÇALVES DOS SANTOS", "FUNÇÃO": "ELETRICISTA MONTADOR"},  
        {"NOME": "ANDERSON MORAES MONTEIRO", "FUNÇÃO": "ELETRICISTA MONTADOR"},  
        {"NOME": "EDMILSON ASSUNÇÃO RIBEIRO", "FUNÇÃO": "ELETRICISTA F/C"},  
        {"NOME": "LUCIANO TAVARES PINTO", "FUNÇÃO": "ELETRICISTA F/C"},  
        {"NOME": "RICARDO DE JESUS SANTOS", "FUNÇÃO": "ELETRICISTA F/C"}  
    ],  

    "ANDERSON": [  
        {"NOME": "RAFAEL FARIA", "FUNÇÃO": "ENG. ELETRICISTA"},  
        {"NOME": "RÉGIS TRAJANO", "FUNÇÃO": "SUPERVISOR DE ELÉTRICA/INSTRUMENTAÇÃO"},  
        {"NOME": "ANDERSON SABINO", "FUNÇÃO": "ENCARREGADO DE INSTRUMENTAÇÃO"},  
        {"NOME": "LUCAS RODRIGUES FALCÃO", "FUNÇÃO": "ELETRICISTA F/C"},  
        {"NOME": "ELCIO DAS NEVES", "FUNÇÃO": "INSTRUMENTISTA"}  
    ],  
    #COMISSIONAMENTO
    "ELIEZER": [  
        {"NOME": "ELIEZER GONÇALVES", "FUNÇÃO": "ENCARREGADO DE TUBULAÇÃO"},  
        {"NOME": "SILVERTINA DA COSTA LIMA", "FUNÇÃO": "SOLDADOR TIG/ER"},  
        {"NOME": "JOSE FRANCISCO RESENDE", "FUNÇÃO": "ENCANADOR"},  
        {"NOME": "RAFAEL DE SOUZA SANTOS", "FUNÇÃO": "ENCANADOR"},  
        {"NOME": "DOUGLIMAR ROCHA", "FUNÇÃO": "ENCANADOR"},  
        {"NOME": "ALEX DONIZETTI DOS SANTOS", "FUNÇÃO": "ENCANADOR"},  
        {"NOME": "ANTONIO DE PAULA DE OLIVEIRA", "FUNÇÃO": "ENCANADOR"},  
        {"NOME": "ALAN BACELAR", "FUNÇÃO": "ENCANADOR"},  
        {"NOME": "EVANILSO DE SOUZA TRINDADE", "FUNÇÃO": "ENCANADOR"}  
    ],  

    "FABIO": [  
        {"NOME": "FABIO CRISPIM", "FUNÇÃO": "ENCARREGADO DE TUBULAÇÃO"}  
    ],  
    #PINTURA
    "LUIZINHO": [  
        {"NOME": "MARCIO MARTINS", "FUNÇÃO": "SUPERVISOR DE CIVIL"},  
        {"NOME": "LUIZ EDUARDO DE ALMEIDA", "FUNÇÃO": "ENC. PINTURA"},  
        {"NOME": "JOEMILSON OTAVIO LUSTOSA", "FUNÇÃO": "PINTOR"},  
        {"NOME": "THIAGO HENRIQUE SILVA", "FUNÇÃO": "PINTOR"},  
        {"NOME": "JOÃO CARLOS RODRIGUES SALES", "FUNÇÃO": "PINTOR"},  
        {"NOME": "ERIVALDO PEREIRA GOMES", "FUNÇÃO": "PINTOR"},  
        {"NOME": "ROBSON DA SILVA COSTA", "FUNÇÃO": "AJUDANTE"},  
        {"NOME": "JACKSON GOMES", "FUNÇÃO": "PINTOR"}  
    ],  
    #CIVIL
    "FRANCISCO": [  
        {"NOME": "MARCIO MARTINS", "FUNÇÃO": "SUPERVISOR DE CIVIL"},  
        {"NOME": "FRANCISCO CARLOS ALVES DE MORAIS", "FUNÇÃO": "ENCARREGADO DE CIVIL"},  
        {"NOME": "RENATO MARQUES DOS SANTOS", "FUNÇÃO": "ENCARREGADO DE CIVIL"},  
        {"NOME": "LUIZ ROBERTO MENEZES", "FUNÇÃO": "OPERADOR DE RETROESCAVADEIRA"},  
        {"NOME": "JOSE FRANCISCO DE CARVALHO", "FUNÇÃO": "PEDREIRO"},  
        {"NOME": "MODESTO PEREIRA DOS SANTOS", "FUNÇÃO": "PEDREIRO"},  
        {"NOME": "LUIZ GOMES DOS SANTOS", "FUNÇÃO": "ARMADOR"},  
        {"NOME": "JOÃO BATISTA MODESTO DA SILVA", "FUNÇÃO": "AJUDANTE"},  
        {"NOME": "RAIMUNDO GINO DA SILVA SOBRINHO", "FUNÇÃO": "CARPINTEIRO"},  
        {"NOME": "JOSE RIBAMAR DO NASCIMENTO PEREIRA", "FUNÇÃO": "CARPINTEIRO"},  
        {"NOME": "MARCOS PEREIRA DE OLIVEIRA", "FUNÇÃO": "ARMADOR"}  
    ],  
    "GERIVALDO": [
        {"NOME": "GERIVALDO SILVA SOUZA", "FUNÇÃO": "ENCARREGADO DE TUBULAÇÃO"},
        {"NOME": "JONATAS FERREIRA", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},
        {"NOME": "NIELSON CASAIS DOS SANTOS", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},
        {"NOME": "RENILTON CASAIS PINTO", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},
        {"NOME": "UENDEL ROSA DOS SANTOS", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},
        {"NOME": "GEFFERSON PHILIPE RODRIGUES", "FUNÇÃO": "ENCANADOR INDUSTRIAL"},
        {"NOME": "DANILO CORREIA DOS SANTOS", "FUNÇÃO": "ENCANADOR INDUSTRIAL"}
    ],

}

